"""empty message

Revision ID: 184e8ed8e2fe
Revises: 
Create Date: 2022-04-20 23:36:52.368581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184e8ed8e2fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scooterId', sa.Integer(), nullable=True),
    sa.Column('locationID', sa.Integer(), nullable=True),
    sa.Column('dateMade', sa.DateTime(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.Column('duration', sa.DateTime(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['locationID'], ['location.id'], ),
    sa.ForeignKeyConstraint(['scooterId'], ['scooter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scooterId', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('surName', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cardNum', sa.String(length=16), nullable=True),
    sa.Column('expireDate', sa.String(length=5), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('locationID', sa.Integer(), nullable=True),
    sa.Column('dateMade', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.DateTime(), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['locationID'], ['location.id'], ),
    sa.ForeignKeyConstraint(['scooterId'], ['scooter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('LocationName', sa.String(length=50), nullable=True),
    sa.Column('totalBookings', sa.Integer(), nullable=True),
    sa.Column('bookingThisMonth', sa.Integer(), nullable=True),
    sa.Column('bookingsPCM', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hourlyRate', sa.Float(), nullable=True),
    sa.Column('fourHourRate', sa.Float(), nullable=True),
    sa.Column('dailyRate', sa.Float(), nullable=True),
    sa.Column('weeklyRate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scooter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('currentBookingID', sa.Integer(), nullable=True),
    sa.Column('currentGuestBookingID', sa.Integer(), nullable=True),
    sa.Column('locationID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currentBookingID'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['currentGuestBookingID'], ['guest_book.id'], ),
    sa.ForeignKeyConstraint(['locationID'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('weeklyHours', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('surName', sa.String(length=20), nullable=True),
    sa.Column('mobileNum', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cardNum', sa.String(length=16), nullable=True),
    sa.Column('expireDate', sa.String(length=5), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issueText', sa.String(length=500), nullable=True),
    sa.Column('devComments', sa.String(length=500), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.Column('employeeId', sa.Integer(), nullable=True),
    sa.Column('scooterId', sa.Integer(), nullable=True),
    sa.Column('dateMade', sa.DateTime(), nullable=True),
    sa.Column('Prio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employeeId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scooterId'], ['scooter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue')
    op.drop_table('user')
    op.drop_table('scooter')
    op.drop_table('rates')
    op.drop_table('location')
    op.drop_table('guest_book')
    op.drop_table('booking')
    # ### end Alembic commands ###
